MODEL:
  META_ARCHITECTURE: "Classifier"
  WEIGHTS: "checkpoints/pytorch/R-18.pth"
  NORMALIZE_INPUT: True
  STANDARDIZE_INPUT: True
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  CLS_HEAD:
    TYPE: 'linear'
    NUM_CLASSES: 1000
    IN_FEATURES: ["res5"]
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
    RES5_DILATION: 1
    NUM_GROUPS: 1
    OUT_FEATURES: ["res5"]  # res4 for C4 backbone, res2..5 for FPN backbone
    STRIDE_IN_1X1: False # according to original comments, should be false
INPUT:
  FORMAT: "RGB"