MODEL:
  META_ARCHITECTURE: "Classifier"
  WEIGHTS: "checkpoints/vit/L-16.pth"
  NORMALIZE_INPUT: True
  STANDARDIZE_INPUT: True
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
  CLS_HEAD:
    TYPE: 'linear'
    NUM_CLASSES: 1000
    IN_FEATURES: ["last"]
  VIT:
    NAME: L_16_imagenet1k
  BACKBONE:
    NAME: build_vit_backbone
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TEST: 384
  RESIZE_MODE: 'standard'
  CROP:
    ENABLED: False